server:
  port: 8083

spring:
  application:
    name: task-event-service

  datasource:
    url: jdbc:mysql://localhost:3306/eventify
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.angeldevs.taskeventservices.shared.infrastructure.persistence.jpa.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  boot:
    admin:
      client:
        url: http://localhost:9090

documentation:
  application:
    description: "@project.description@"
    version: "@project.version@"

authorization:
  jwt:
    secret: 14db3b405fd39d8a7434ea25d19e80eba402da04a4807ffa95114e92a140dd1c
    expiration:
      days: 7

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
